# Generated by Django 3.1 on 2020-10-11 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_excerpt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_time']},
        ),
    ]
